services:
  # Zookeeper service
  zookeeper:
    image: bitnami/zookeeper:3.7.0
    container_name: zookeeper
    ports:
      - '2181:2181'
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
  # Kafka service
  kafka:
    image: wurstmeister/kafka:2.12-2.5.0
    container_name: kafka
    ports:
      - '9092:9092'
    expose:
      - '9092'
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092  # Specify where Kafka should listen
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092  # External address for other containers
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    depends_on:
      - zookeeper

  # Discovery service
  order-discovery-service:
    build: ./discovery-service
    container_name: discovery-service
    expose:
      - '8761'
    ports:
      - '8761:8761'
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8761/actuator/health"]
      interval: 10s
      retries: 4

  # Gateway service
  order-gateway-service:
    build: ./gateway-service
    container_name: gateway-service
    expose:
      - '8888'
    ports:
      - '8888:8888'
    environment:
      - DISCOVRY_SERVICE_URL=http://order-discovery-service:8761/eureka
    depends_on:
      order-discovery-service:
        condition: service_healthy

  # Customer service
  order-customer-service:
    build: ./customer-service
    container_name: customer-service
    expose:
      - '8080'
    ports:
      - '8080:8080'
    environment:
      - DISCOVRY_SERVICE_URL=http://order-discovery-service:8761/eureka
      - SPRING_KAFKA_BOOTSTRAP_SERVERS=kafka:9092
    depends_on:
      order-discovery-service:
        condition: service_healthy
      kafka:
        condition: service_started

  # Order service
  order-order-service:
    build: ./order-service
    container_name: order-service
    expose:
      - '8081'
    ports:
      - '8081:8081'
    environment:
      - DISCOVRY_SERVICE_URL=http://order-discovery-service:8761/eureka
      - SPRING_KAFKA_BOOTSTRAP_SERVERS=kafka:9092
    depends_on:
      order-discovery-service:
        condition: service_healthy
      kafka:
        condition: service_started

  # Notification service
  order-notification-service:
    build: ./notification-service
    container_name: notification-service
    expose:
      - '8089'
    ports:
      - '8089:8089'
    environment:
      - DISCOVRY_SERVICE_URL=http://order-discovery-service:8761/eureka
      - SPRING_KAFKA_BOOTSTRAP_SERVERS=kafka:9092
    depends_on:
      order-discovery-service:
        condition: service_healthy
      kafka:
        condition: service_started

  # Payment service
  order-payment-service:
    build: ./payment-service
    container_name: payment-service
    expose:
      - '8088'
    ports:
      - '8088:8088'
    environment:
      - DISCOVRY_SERVICE_URL=http://order-discovery-service:8761/eureka
      - SPRING_KAFKA_BOOTSTRAP_SERVERS=kafka:9092
    depends_on:
      order-discovery-service:
        condition: service_healthy
      kafka:
        condition: service_started
